"""
FemCare AI recipe library.

Recipes are vegetarian wellness options. The recommendation engine filters
this library using dietary preference, allergies, dislikes and wellness goals.
Nutrition values are approximate and are for general wellness guidance only.
"""

def _recipe(slug, name, meal_type, ingredients, tags, calories, protein, fiber, iron, steps, diet_type="Vegetarian"):
    return {
        "slug": slug,
        "name": name,
        "meal_type": meal_type,
        "ingredients": ingredients,
        "tags": tags,
        "calories": calories,
        "protein": protein,
        "fiber": fiber,
        "iron": iron,
        "steps": steps,
        "diet_type": diet_type,
    }


RECIPE_LIBRARY = [
    # ---------------- BREAKFAST ----------------
    _recipe("vegetable_oats_upma","Vegetable Oats Upma","breakfast",
        ["oats","carrot","beans","peas","onion","spices"],
        ["balanced","high_fiber","pcos","diabetes","thyroid"],280,9,6,2.2,
        ["Dry roast oats lightly.","Saute vegetables and spices with a little water or oil.","Add oats and water, cook until soft and serve warm."]),
    _recipe("moong_chilla","Moong Dal Chilla","breakfast",
        ["moong dal","carrot","coriander","cumin","lemon"],
        ["protein","high_fiber","pcos","diabetes","anemia"],260,13,6,3.1,
        ["Soak moong dal and blend into a smooth batter.","Mix vegetables and spices into the batter.","Cook thin chillas on a hot pan and finish with lemon."]),
    _recipe("spinach_moong_chilla","Spinach Moong Chilla","breakfast",
        ["moong dal","spinach","lemon","cumin","coriander"],
        ["protein","iron_rich","anemia","pcos","high_fiber"],250,13,7,4.0,
        ["Blend soaked moong dal with spinach.","Season the batter and rest briefly.","Cook both sides until done and serve with lemon."]),
    _recipe("vegetable_poha","Vegetable Poha","breakfast",
        ["poha","peas","carrot","onion","lemon","coriander"],
        ["balanced","high_fiber","vegetarian"],270,6,4,2.0,
        ["Rinse poha and drain.","Cook vegetables with spices and add poha.","Steam briefly and finish with lemon and coriander."]),
    _recipe("vegetable_ragi_dosa","Vegetable Ragi Dosa","breakfast",
        ["ragi flour","rice flour","carrot","onion","coriander"],
        ["fiber","iron_rich","anemia","balanced"],290,7,5,3.2,
        ["Mix ragi and rice flour with water.","Add finely chopped vegetables and spices.","Spread thinly on a hot pan and cook until crisp."]),
    _recipe("ragi_vegetable_upma","Ragi Vegetable Upma","breakfast",
        ["ragi rava","carrot","beans","peas","coriander"],
        ["fiber","iron_rich","anemia","pcos"],285,8,6,3.4,
        ["Toast ragi rava lightly.","Cook vegetables with spices and water.","Add ragi rava gradually and cook until fluffy."]),
    _recipe("vegetable_dalia","Vegetable Dalia Bowl","breakfast",
        ["broken wheat","carrot","beans","peas","cumin"],
        ["high_fiber","pcos","diabetes","balanced"],300,9,7,2.5,
        ["Roast broken wheat lightly.","Cook vegetables with cumin and water.","Add dalia and simmer until soft."]),
    _recipe("sprouts_breakfast_bowl","Sprouts Breakfast Bowl","breakfast",
        ["moong sprouts","cucumber","tomato","carrot","lemon"],
        ["protein","high_fiber","pcos","diabetes"],230,11,7,3.0,
        ["Steam sprouts if desired for food safety.","Add chopped vegetables.","Season with lemon and mild spices."]),
    _recipe("fruit_oats_bowl","Apple Cinnamon Oats Bowl","breakfast",
        ["oats","apple","cinnamon","water","pumpkin seeds"],
        ["fiber","balanced"],290,8,7,2.3,
        ["Cook oats with water until creamy.","Add chopped apple and cinnamon.","Top with pumpkin seeds if tolerated."]),
    _recipe("banana_chia_oats","Banana Chia Oats","breakfast",
        ["oats","banana","chia seeds","cinnamon","water"],
        ["fiber","balanced"],300,8,8,2.4,
        ["Cook oats until soft.","Stir in mashed banana and cinnamon.","Top with chia seeds and serve."]),
    _recipe("chia_fruit_pudding","Chia Fruit Pudding","breakfast",
        ["chia seeds","oat milk","apple","berries","cinnamon"],
        ["fiber","balanced"],260,7,9,2.6,
        ["Mix chia seeds with oat milk.","Chill until thick.","Top with chopped fruit before serving."]),
    _recipe("coconut_chia_pudding","Coconut Chia Pudding","breakfast",
        ["chia seeds","coconut milk","papaya","cinnamon"],
        ["fiber","balanced"],270,6,8,2.3,
        ["Combine chia seeds and coconut milk.","Refrigerate until set.","Top with papaya and cinnamon."]),
    # ---------------- SNACKS ----------------
    _recipe("fresh_fruit_bowl","Fresh Fruit Bowl","snack",
        ["apple","papaya","guava","orange"],
        ["balanced","high_fiber","vitamin_c"],160,3,5,1.2,
        ["Wash the fruits.","Cut into bite-sized pieces.","Combine and serve fresh."]),
    _recipe("beetroot_apple_bowl","Beetroot Apple Bowl","snack",
        ["beetroot","apple","lemon","coriander"],
        ["iron_rich","anemia","high_fiber"],170,3,5,2.0,
        ["Cook or steam beetroot and cool.","Add chopped apple.","Finish with lemon and coriander."]),
    _recipe("roasted_chickpeas","Roasted Chickpeas","snack",
        ["chickpeas","cumin","paprika","lemon"],
        ["protein","high_fiber","pcos","diabetes","anemia"],190,9,7,2.5,
        ["Use cooked and drained chickpeas.","Roast until lightly crisp with spices.","Cool slightly and finish with lemon."]),
    _recipe("apple_chickpea_bowl","Apple Roasted Chickpea Bowl","snack",
        ["apple","roasted chickpeas","cinnamon"],
        ["protein","fiber","pcos","diabetes"],210,8,6,2.2,
        ["Slice apple.","Combine with roasted chickpeas.","Add a pinch of cinnamon."]),
    _recipe("cucumber_chana_chaat","Cucumber Chana Chaat","snack",
        ["chickpeas","cucumber","tomato","lemon","coriander"],
        ["protein","high_fiber","pcos","diabetes"],200,9,7,2.7,
        ["Combine cooked chickpeas and vegetables.","Add lemon and mild spices.","Mix and serve fresh."]),
    _recipe("sprouts_lemon_bowl","Lemon Sprouts Bowl","snack",
        ["moong sprouts","cucumber","tomato","lemon"],
        ["protein","fiber","pcos"],150,9,5,2.4,
        ["Steam sprouts if desired.","Add chopped vegetables.","Season with lemon and mild spices."]),
    _recipe("roasted_makhana","Roasted Makhana","snack",
        ["makhana","cumin","black pepper"],
        ["light","balanced"],150,5,3,1.0,
        ["Dry roast makhana until crisp.","Add cumin and pepper.","Cool and serve."]),
    _recipe("fruit_seed_bowl","Fruit Seed Bowl","snack",
        ["apple","papaya","sunflower seeds","pumpkin seeds"],
        ["fiber","balanced"],220,6,6,2.0,
        ["Wash and chop fruit.","Add seeds if tolerated.","Serve immediately."]),
    _recipe("carrot_hummus_plate","Carrot Hummus Plate","snack",
        ["carrot","chickpeas","lemon","cumin"],
        ["protein","fiber","pcos"],190,7,6,2.4,
        ["Blend cooked chickpeas with lemon and cumin.","Slice carrots.","Serve carrots with hummus."]),
    _recipe("guava_chana_bowl","Guava Chana Bowl","snack",
        ["guava","roasted chickpeas","lemon","coriander"],
        ["fiber","protein","vitamin_c","anemia"],190,7,7,2.6,
        ["Chop guava.","Add roasted chickpeas.","Finish with lemon and coriander."]),
    # ---------------- LUNCH ----------------
    _recipe("spinach_dal_brown_rice","Spinach Dal Brown Rice","lunch",
        ["spinach","toor dal","brown rice","lemon","cumin"],
        ["protein","iron_rich","anemia","high_fiber"],430,16,10,4.5,
        ["Cook brown rice.","Prepare dal with spinach and cumin.","Serve together and add lemon."]),
    _recipe("protein_vegetable_rice_bowl","Protein Vegetable Rice Bowl","lunch",
        ["brown rice","moong dal","beans","carrot","peas"],
        ["protein","high_fiber","pcos","diabetes"],440,17,10,3.8,
        ["Cook brown rice and dal separately.","Saute or steam mixed vegetables.","Combine into a bowl and season lightly."]),
    _recipe("moong_vegetable_bowl","Moong Vegetable Bowl","lunch",
        ["moong dal","carrot","beans","spinach","brown rice"],
        ["protein","fiber","pcos","diabetes","anemia"],420,18,11,4.2,
        ["Cook moong dal until tender.","Prepare mixed vegetables.","Serve with a moderate portion of brown rice."]),
    _recipe("chickpea_rice_bowl","Chickpea Brown Rice Bowl","lunch",
        ["chickpeas","brown rice","cucumber","tomato","spinach"],
        ["protein","fiber","pcos","diabetes"],450,15,12,4.0,
        ["Cook chickpeas and brown rice.","Add chopped vegetables and spinach.","Combine and season with lemon."]),
    _recipe("lentil_vegetable_bowl","Lentil Vegetable Bowl","lunch",
        ["lentils","spinach","carrot","beans","lemon"],
        ["protein","iron_rich","anemia","high_fiber"],390,18,12,5.0,
        ["Cook lentils until tender.","Add vegetables and simmer.","Finish with lemon and serve warm."]),
    _recipe("vegetable_millet_bowl","Vegetable Millet Bowl","lunch",
        ["foxtail millet","carrot","beans","peas","moong dal"],
        ["high_fiber","protein","pcos","diabetes"],410,14,9,3.2,
        ["Cook millet until fluffy.","Prepare moong dal and vegetables.","Combine and season lightly."]),
    _recipe("vegetable_dal_khichdi","Vegetable Dal Khichdi","lunch",
        ["moong dal","rice","carrot","peas","spinach"],
        ["balanced","protein","easy_digest"],390,15,8,3.5,
        ["Wash rice and dal.","Cook with vegetables and water until soft.","Season mildly and serve warm."]),
    _recipe("quinoa_moong_bowl","Quinoa Moong Protein Bowl","lunch",
        ["quinoa","moong dal","cucumber","carrot","spinach"],
        ["protein","fiber","pcos","diabetes"],410,17,9,4.0,
        ["Cook quinoa and moong dal.","Add fresh vegetables.","Combine and season with lemon and herbs."]),
    _recipe("rajma_brown_rice","Rajma Brown Rice Bowl","lunch",
        ["rajma","brown rice","tomato","onion","coriander"],
        ["protein","fiber","pcos","diabetes"],450,16,11,4.1,
        ["Cook soaked rajma until tender.","Prepare a tomato-based rajma mixture.","Serve with brown rice and coriander."]),
    _recipe("dal_spinach_soup_lunch","Lentil Spinach Soup Bowl","lunch",
        ["lentils","spinach","carrot","tomato","cumin"],
        ["protein","iron_rich","anemia","high_fiber"],350,17,10,4.8,
        ["Cook lentils with tomato and carrot.","Add spinach near the end.","Simmer briefly and serve warm."]),
    # ---------------- EVENING ----------------
    _recipe("spinach_sprouts_salad","Spinach Sprouts Salad","evening",
        ["spinach","moong sprouts","tomato","lemon","cucumber"],
        ["protein","iron_rich","anemia","high_fiber"],170,9,5,3.0,
        ["Wash vegetables well.","Combine spinach, sprouts and vegetables.","Add lemon and mild seasoning."]),
    _recipe("chickpea_sprouts_salad","Chickpea Sprouts Salad","evening",
        ["chickpeas","moong sprouts","tomato","cucumber","lemon"],
        ["protein","fiber","pcos","diabetes"],220,11,7,3.2,
        ["Combine cooked chickpeas and sprouts.","Add chopped vegetables.","Season with lemon and serve."]),
    _recipe("vegetable_sprouts_salad","Vegetable Sprouts Salad","evening",
        ["moong sprouts","tomato","cucumber","carrot","lemon"],
        ["protein","fiber","balanced"],160,8,5,2.5,
        ["Steam sprouts if desired.","Add chopped vegetables.","Season with lemon and herbs."]),
    _recipe("green_tea_makhana","Green Tea & Makhana Snack","evening",
        ["makhana","green tea","cinnamon"],
        ["light","balanced"],120,4,2,0.8,
        ["Roast makhana until crisp.","Prepare green tea separately.","Enjoy without added sugar."]),
    _recipe("mint_tea_fruit","Mint Tea & Fruit Plate","evening",
        ["mint","green apple","guava","lemon"],
        ["light","vitamin_c"],130,2,4,1.1,
        ["Prepare unsweetened mint tea.","Slice fruit.","Serve together."]),
    _recipe("lemon_ginger_tea","Lemon Ginger Herbal Tea","evening",
        ["ginger","lemon","water"],
        ["light","hydration"],20,0,0,0.1,
        ["Simmer ginger in water.","Strain into a cup.","Add lemon after cooling slightly."]),
    _recipe("cucumber_chana_salad","Cucumber Chana Salad","evening",
        ["chickpeas","cucumber","tomato","coriander","lemon"],
        ["protein","fiber","pcos"],200,9,7,2.7,
        ["Combine chickpeas and chopped vegetables.","Add coriander and lemon.","Mix and serve."]),
    _recipe("fruit_coconut_bowl","Fruit Coconut Bowl","evening",
        ["papaya","apple","coconut flakes"],
        ["fiber","balanced"],170,2,5,1.0,
        ["Chop fruit.","Add a small amount of coconut flakes.","Serve fresh."]),
    _recipe("roasted_lentil_snack","Roasted Lentil Snack","evening",
        ["roasted lentils","cumin","pepper","lemon"],
        ["protein","fiber"],180,10,6,2.8,
        ["Use cooked lentils and dry-roast until crisp.","Season with cumin and pepper.","Finish with lemon."]),
    _recipe("herbal_tea_chia_bowl","Herbal Tea & Chia Fruit Bowl","evening",
        ["chia seeds","papaya","mint","lemon"],
        ["fiber","light"],150,4,6,1.8,
        ["Prepare unsweetened mint tea.","Combine fruit and chia seeds.","Serve as a light snack."]),
    # ---------------- DINNER ----------------
    _recipe("vegetable_moong_soup","Vegetable Moong Soup","dinner",
        ["moong dal","spinach","carrot","beans","cumin"],
        ["protein","light","anemia","pcos"],300,16,8,4.0,
        ["Cook moong dal until soft.","Add vegetables and simmer.","Season lightly and serve warm."]),
    _recipe("ragi_chapati_dal","Ragi Chapati with Dal","dinner",
        ["ragi flour","moong dal","spinach","cumin"],
        ["protein","iron_rich","anemia"],390,15,8,4.2,
        ["Prepare soft ragi chapatis.","Cook moong dal with spinach.","Serve together with mild seasoning."]),
    _recipe("whole_wheat_vegetable_chapati","Whole Wheat Vegetable Chapati","dinner",
        ["whole wheat flour","carrot","spinach","cumin","moong dal"],
        ["protein","fiber","balanced"],400,14,8,3.4,
        ["Prepare chapati dough.","Cook chapatis and a simple vegetable-dal filling.","Serve warm."]),
    _recipe("moong_vegetable_soup","Moong Vegetable Soup Bowl","dinner",
        ["moong dal","tomato","carrot","spinach","coriander"],
        ["protein","light","pcos","diabetes"],290,15,7,3.8,
        ["Cook moong dal with tomato.","Add vegetables and simmer.","Finish with coriander."]),
    _recipe("lentil_spinach_bowl","Lentil Spinach Bowl","dinner",
        ["lentils","spinach","carrot","cucumber","lemon"],
        ["protein","iron_rich","anemia","high_fiber"],330,17,9,4.7,
        ["Cook lentils.","Add spinach and carrot.","Serve with cucumber and lemon."]),
    _recipe("vegetable_dalia_dinner","Savory Vegetable Dalia","dinner",
        ["broken wheat","carrot","beans","peas","moong dal"],
        ["fiber","protein","pcos","diabetes"],350,12,8,3.0,
        ["Cook dalia with vegetables and moong dal.","Simmer until soft.","Season lightly and serve warm."]),
    _recipe("quinoa_vegetable_bowl","Quinoa Vegetable Protein Bowl","dinner",
        ["quinoa","moong sprouts","spinach","carrot","cucumber"],
        ["protein","fiber","pcos","diabetes"],360,14,8,3.4,
        ["Cook quinoa.","Add cooked sprouts and vegetables.","Season with lemon and herbs."]),
    _recipe("vegetable_soup_salad","Vegetable Soup & Salad","dinner",
        ["carrot","tomato","spinach","cucumber","moong sprouts"],
        ["light","fiber","balanced"],260,9,7,3.0,
        ["Prepare a simple vegetable soup.","Combine fresh salad vegetables.","Serve soup and salad together."]),
    _recipe("moong_chapati_plate","Moong Dal & Chapati Plate","dinner",
        ["whole wheat flour","moong dal","spinach","cucumber"],
        ["protein","fiber","balanced"],390,16,8,3.8,
        ["Prepare chapatis.","Cook moong dal with spinach.","Serve with cucumber."]),
    _recipe("millet_lentil_dinner","Millet Lentil Dinner Bowl","dinner",
        ["little millet","lentils","carrot","beans","spinach"],
        ["protein","fiber","pcos","diabetes","anemia"],370,16,9,4.3,
        ["Cook millet and lentils.","Steam or saute vegetables.","Combine and season lightly."]),
]


    # ---------------- NON-VEGETARIAN ----------------
    _recipe("chicken_spinach_bowl","Chicken Spinach Protein Bowl","lunch",
        ["chicken","spinach","brown rice","carrot","lemon"],
        ["protein","high_fiber","pcos","diabetes","anemia"],460,34,8,4.0,
        ["Cook chicken thoroughly until no longer pink.","Prepare spinach and vegetables.","Serve with a moderate portion of brown rice and lemon."],
        "Non-vegetarian"),
    _recipe("grilled_chicken_salad","Grilled Chicken Salad","lunch",
        ["chicken","lettuce","cucumber","tomato","lemon"],
        ["protein","high_fiber","pcos","diabetes"],320,32,5,2.2,
        ["Cook chicken thoroughly on a hot pan.","Combine with washed vegetables.","Dress with lemon and mild herbs."],
        "Non-vegetarian"),
    _recipe("fish_vegetable_bowl","Fish Vegetable Brown Rice Bowl","lunch",
        ["fish","brown rice","spinach","carrot","lemon"],
        ["protein","balanced","pcos"],430,30,6,2.5,
        ["Cook fish thoroughly using a simple method.","Prepare vegetables and brown rice.","Serve with lemon."],
        "Non-vegetarian"),
    _recipe("chicken_lentil_soup","Chicken Lentil Soup","dinner",
        ["chicken","lentils","carrot","spinach","cumin"],
        ["protein","iron_rich","anemia","pcos"],360,31,8,4.4,
        ["Cook chicken thoroughly.","Simmer lentils with vegetables.","Add cooked chicken and serve hot."],
        "Non-vegetarian"),
    _recipe("chicken_vegetable_soup","Chicken Vegetable Soup","dinner",
        ["chicken","carrot","beans","spinach","tomato"],
        ["protein","light","balanced"],300,30,5,2.4,
        ["Cook chicken thoroughly.","Simmer vegetables until tender.","Add cooked chicken and season lightly."],
        "Non-vegetarian"),
    _recipe("fish_spinach_plate","Fish & Spinach Plate","dinner",
        ["fish","spinach","cucumber","tomato","lemon"],
        ["protein","iron_rich","light"],290,29,4,2.6,
        ["Cook fish thoroughly.","Prepare spinach and fresh vegetables.","Serve together with lemon."],
        "Non-vegetarian"),
    _recipe("chicken_sprouts_salad","Chicken Sprouts Salad","evening",
        ["chicken","moong sprouts","cucumber","tomato","lemon"],
        ["protein","high_fiber","pcos","diabetes"],260,27,6,2.4,
        ["Cook chicken thoroughly and cool slightly.","Combine with cooked/steamed sprouts and vegetables.","Finish with lemon."],
        "Non-vegetarian"),
    _recipe("chicken_vegetable_wrap","Chicken Vegetable Whole Wheat Wrap","breakfast",
        ["chicken","whole wheat flour","spinach","carrot","cucumber"],
        ["protein","high_fiber","balanced"],390,28,7,3.0,
        ["Cook chicken thoroughly and slice.","Prepare a whole wheat wrap with vegetables.","Fill, roll and serve warm."],
        "Non-vegetarian"),
    _recipe("egg_vegetable_chilla","Egg Vegetable Chilla","breakfast",
        ["egg","carrot","spinach","onion","coriander"],
        ["protein","balanced","pcos","anemia"],250,16,3,2.2,
        ["Whisk eggs with chopped vegetables.","Cook on a lightly heated pan until fully set.","Serve warm."],
        "Eggetarian"),
    _recipe("egg_spinach_bowl","Egg Spinach Breakfast Bowl","breakfast",
        ["egg","spinach","tomato","cucumber","lemon"],
        ["protein","iron_rich","anemia","balanced"],240,17,3,2.5,
        ["Cook eggs until fully set.","Combine with washed vegetables and spinach.","Serve with lemon."],
        "Eggetarian"),
    _recipe("egg_chickpea_salad","Egg Chickpea Salad","snack",
        ["egg","chickpeas","cucumber","tomato","lemon"],
        ["protein","fiber","pcos"],260,16,6,2.7,
        ["Cook egg until fully set and chop.","Combine with cooked chickpeas and vegetables.","Add lemon and mild seasoning."],
        "Eggetarian"),
    _recipe("egg_vegetable_soup","Egg Vegetable Soup","dinner",
        ["egg","spinach","carrot","beans","tomato"],
        ["protein","light","balanced"],230,15,5,2.1,
        ["Prepare a light vegetable soup.","Add beaten egg gradually while stirring.","Cook until egg is fully set and serve hot."],
        "Eggetarian"),


RECIPE_BY_SLUG = {recipe["slug"]: recipe for recipe in RECIPE_LIBRARY}
